### ISSUE TITLE
Country not fetching 

### ISSUE THREAD

**Issue by quantkun** [houseofai/tvscreener#19]
ss.set_markets(StocksMarket.KOREA)
Not working 

As default is set to America 
And then not allowing to bypass the default settings.

Trying in Google Collab.
Pls help

**Comment by houseofai** [comment]
There was an old reference to `StocksMarket` in the documentation. The correct one is `Market`
Try:
```
import tvscreener as tvs
from tvscreener import Market

ss = tvs.StockScreener()
ss.set_markets(Market.KOREA)
ss.set_range(0, 10000)
df = ss.get()
df
```

It will return 3794 results:
![korea](https://github.com/houseofai/tvscreener/assets/8287111/a20c734d-5bd8-469c-8f06-244b661d0bde)
